services:
  - type: web
    name: stock-app
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 10000
    pythonVersion: 3.9
